version: '3.7'
networks:
  qr-code-nw:
services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    networks: 
      - qr-code-nw
  qr-code-prices-server:
    build: .
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    ports:
      - 8888:8888
      - 9229:9229
    networks: 
      - qr-code-nw
    depends_on:
      - mongodb_container
    command: yarn start
 
    